 select 利用者名, 
        オブジェクト名, 
        コントロール名, 
        convert(int,isnull(キー1,0)) as  AS 動作コード, 
        convert(int,isnull(キー4,0)) as 頁, 
        convert(int,isnull(キー5,0)) as 行, 
        isnull(列1,'') as 列1, 
        isnull(列2,'') as 列2, 
        isnull(列3,'') as 列3, 
        isnull(列4,'') as 列4, 
        isnull(列5,'') as 列5, 
        isnull(列6,'') as 列6, 
        isnull(列7,'') as 列7, 
        isnull(列8,'') as 列8, 
        isnull(列9,'') as 列9, 
        isnull(列10,'') as 列10, 
        isnull(列11,'') as 列11, 
        isnull(列12,'') as 列12, 
        isnull(列13,'') as 列13, 
        isnull(列14,'') as 列14, 
        isnull(列15,'') as 列15, 
        isnull(列16,'') as 列16, 
        isnull(列17,'') as 列17, 
        isnull(列18,'') as 列18, 
        isnull(列19,'') as 列19, 
        isnull(列20,'') as 列20, 
        isnull(列21,'') as 列21, 
        isnull(列22,'') as 列22, 
        isnull(列23,'') as 列23, 
        isnull(列24,'') as 列24, 
        isnull(列25,'') as 列25, 
        isnull(列26,'') as 列26, 
        isnull(列27,'') as 列27, 
        isnull(列28,'') as 列28, 
        isnull(列29,'') as 列29, 
        isnull(列30,'') as 列30 
 from 汎用登録_T as t000 
 where (オブジェクト名='車両運転認定証_F') 
  and (コントロール名='車両運転認定証_F') 
  and (convert(int,isnull(キー1,0)) between 500 and 520) 

